spring:
  application:
    name: authserver
  data:
    mongodb:
      host: auth-mongodb
      port: 27017
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      repositories:
        enabled: true

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/


