server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true        # 指定该Eureka实例的主机名
  client:
    enabled: true
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

