spring:
  data:
    mongodb:
      username: root
      password: root
      database: wantrip
      port: 27017

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/