eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  data:
    mongodb:
#      username: root
#      password: root
#      database: wantrip
#      port: 27017
      host: auth-mongodb
      port: 27017
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      repositories:
        enabled: true

server:
  port: 8081


#spring.data.mongodb.authentication-database= # Authentication database name.
#spring.data.mongodb.database=test # Database name.
#spring.data.mongodb.field-naming-strategy= # Fully qualified name of the FieldNamingStrategy to use.
#spring.data.mongodb.grid-fs-database= # GridFS database name.
#spring.data.mongodb.host=localhost # Mongo server host.
#spring.data.mongodb.password= # Login password of the mongo server.
#spring.data.mongodb.port=27017 # Mongo server port.
#spring.data.mongodb.repositories.enabled=true # Enable Mongo repositories.
#spring.data.mongodb.uri=mongodb://localhost/test # Mongo database URI. When set, host and port are ignored.
#spring.data.mongodb.username= # Login user of the mongo server.